spring:
  profiles:
    active: dev
#    include:

# --------------------
#spring:
#  profiles:
#    active: dev
#    include:

# --------------------
#spring:
#  profiles:
#    active: dev
#    include:

# --------------------
#spring:
#  profiles:
#    active: dev
#    include: